#!/bin/sh
set -e

##
# variables
target="${1}"
destdir="${2}"

##
# main
cd "${target}"
find . \
     -type f \
     ! -name ".git" \
     ! -path "../.git/*" \
     -exec install -m u=rwx,g=rx,o= "{}" "${destdir}"/"{}" \; \
     -exec echo -n . \;
echo
