#!/bin/sh
set -e

##
# variables
target="${1}"
destdir="${2}"

##
# main
cd "${target}"
find . \
     -type d \
     -exec install -d -m u=rwx,g=rx,o= "${destdir}"/"{}" \;	\
     -exec echo -n . \;
echo
