#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
sharebase="${localbase}"/share/webskel
libexec="${localbase}"/libexec/webskel

##
# main
echo "Skeletons "
find "${sharebase}" \
     -type d \
     -maxdepth 1 \
     -name *.skeleton \
     -exec basename {} \;
