#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
sharebase="${localbase}"/share/webskel
libexec="${localbase}"/libexec/webskel
appname="${1}"
skel="${2}"
target=
destdir=

##
# functions
. "${libexec}"/functions/print.sh

##
# main
if [ -z "${appname}" ]; then
    printerr "provide an application name"
    exit 1
fi
if [ -z "${skel}" ]; then
    printerr "provide a skeleton name"
    exit 1
fi
if [ -e "${sharebase}"/"${skel}".skeleton ]; then
    target="${sharebase}"/"${skel}".skeleton
    destdir="$(pwd)"/"${appname}"
    "${libexec}"/scripts/mkdir "${target}" "${destdir}"
    "${libexec}"/scripts/install "${target}" "${destdir}"
    printok "initialized ${appname}"
else
    printerr "skeleton ${skel} was not found"
    exit 1
fi
